name: Update Repository JSON

on:
  schedule:
    - cron: '*/2 * * * *'  # Run every 2 minutes
  push:
    branches:
      - main  # Trigger on push to main

jobs:
  update-repository-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run CloneRepos.js to Download Plugin JSONs
        run: |
          node CloneRepos.js

      - name: Combine Plugin JSON Files into Repository.json
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

          echo "Checking downloaded files:"
          ls -la plugin_repos

          Repository_json="[]"

          for file in plugin_repos/*.json; do
            if [ -f "$file" ]; then
              echo "Processing: $file"
              if jq empty "$file" 2>/dev/null; then
                plugin_json=$(cat "$file")
                Repository_json=$(echo "$Repository_json" | jq ". += [$plugin_json]")
              else
                echo "Skipping invalid JSON: $file"
              fi
            fi
          done

          echo "$Repository_json" > Repository.json

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          author_email: 'github-actions@github.com'
          message: 'Update Repository.json with new plugins'
