name: Clone and Merge Repositories

on:
  push:
    branches:
      - main  # This triggers on a push to the `main` branch

jobs:
  clone-and-merge:
    runs-on: ubuntu-latest  # We use the latest Ubuntu runner

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3  # This checks out your repository to the runner

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3  # This sets up Node.js
        with:
          node-version: '16'  # Set your desired Node.js version

      # Install dependencies
      - name: Install dependencies
        run: |
          npm init -y  # Initialize a new Node.js project (package.json)
          npm install axios  # Install axios to make HTTP requests

      # Run CloneRepos.js script
      - name: Run CloneRepos.js
        run: |
          node CloneRepos.js  # Execute your script
