name: Update Repository JSON

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes
  push:
    branches:
      - main  # Trigger if there's a push to main branch

jobs:
  update-repository-json:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Node.js (if you need to use Node for processing)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the version of Node.js to use

      # Step 3: Run CloneRepos.js to clone the repositories
      - name: Clone Repositories
        run: |
          node CloneRepos.js  # This will execute CloneRepos.js script

      # Step 4: Combine Plugin JSON Files
      - name: Combine Plugin JSON Files
        run: |
          # Install jq to process JSON files
          sudo apt-get install jq

          # Initialize an empty array for combined data
          combined_json="[]"

          # Process each plugin JSON file in the directory (assuming they're in a folder like "plugins/")
          for file in plugins/*.json; do
            if [ -f "$file" ]; then
              plugin_json=$(cat "$file")
              combined_json=$(echo "$combined_json" | jq ". += [$plugin_json]")
            fi
          done

          # Save the combined result to Repository.json
          echo "$combined_json" > Repository.json

      # Step 5: Commit and Push Changes
      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          author_email: 'github-actions@github.com'
          message: 'Update Repository.json with new plugins'
